server:
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/orderservice
    username: admin
    password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update

  application:
    name: order-service

eureka:
  client:
    service-url:
      defaultZone: http//localhost:8761/eureka/

