server:
  port: 8083

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/inventoryervice
    username: admin
    password: 123456
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  application:
    name: inventory-service

eureka:
  client:
    service-url:
      defaultZone: http//localhost:8761/eureka/


